# Demanda semanal observada y población común
El RAW permanece intacto. La copia analítica elimina transacciones con `cantidad` nula o negativa **antes** de agregar; conserva ceros y no convierte cajas/unidades. El objetivo es cantidad positiva observada en ERP (incluyendo semanas de cero), no saldo neto ni demanda latente.

Agregación `W-SUN`, ceros sólo en huecos interiores del calendario depurado de cada serie. No se extienden los extremos sin evidencia. Corte `2026-01-01`; se excluye del scoring la semana 29-dic a 4-ene. Las semanas de los extremos pueden ser parciales. Las medias móviles usan `shift(1)` y el calendario completo se conserva al calcular lags.

La tabla final se calcula desde la intersección exacta `sucursal + producto + semana` de las predicciones válidas de los cuatro modelos. Las métricas propias quedan separadas. Precisión completa en archivos y cálculos; cuatro decimales sólo en pantalla.

Se conservan lags 1/2/4/8, medias 4/8, mes, semana ISO y trimestre; sin variables contemporáneas ni día de semana. OneHotEncoder dentro del Pipeline, ajustado en cada fold. TimeSeriesSplit(n_splits=3) sobre semanas únicas del TRAIN. Rejillas y semilla 42 sin cambios. ML es secuencial de una semana, con historia observada previa y parámetros fijos.

In [1]:
import sys
from pathlib import Path
import pandas as pd
sys.path.insert(0, str(Path('..').resolve()))
from src.experimento_semanal import SALIDA
pd.options.display.float_format = '{:.4f}'.format
from src.experimento_semanal import ejecutar_ml, ejecutar_comparacion
pipeline, tabla_propia_ml = ejecutar_ml()
display(tabla_propia_ml)
print('Métricas anteriores: cobertura propia ML, no tabla comparativa final.')

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

Random Forest best_params_: {'max_depth': 10, 'min_samples_leaf': 2, 'n_estimators': 200}
Random Forest best_score_ (MSE negativo): -0.2508265715335453

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0, 1] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

XGBoost best_params_: {'learning_rate': 0.05, 'max_depth': 3, 'n_estimators': 100}
XGBoost best_score_ (MSE negativo): -0.2368016580762701

C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
C:\Users\USER\Documents\Codex\2026-09-07\github-plugin-github-openai-curated-remote\work\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:262: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

,Modelo,MAE,RMSE,R2,Observaciones_evaluadas,Series_evaluadas,Best Params,CV neg_MSE
0,Regresión Lineal,0.2174,0.5150,0.3250,3940,156,{},NaN
1,Random Forest,0.2106,0.5233,0.3031,3940,156,"{'max_depth': 10, 'min_samples_leaf': 2, 'n_es...",-0.2508
2,XGBoost,0.2103,0.5238,0.3018,3940,156,"{'learning_rate': 0.05, 'max_depth': 3, 'n_est...",-0.2368

Métricas anteriores: cobertura propia ML, no tabla comparativa final.

## Comparación sobre las mismas observaciones
Requiere ejecutar primero 06 con esta misma versión de código/datos. Se verifican manifiestos y hashes. No se fuerzan rankings ni se redondean valores antes de calcular métricas. Las diferencias de protocolo impiden atribuir las diferencias exclusivamente al algoritmo.

In [2]:
predicciones_comunes, tabla_final, metricas_propias, cobertura = ejecutar_comparacion()
display(tabla_final)
display(cobertura)
for metrica in ['MAE','RMSE','R2']:
    valor = tabla_final[metrica].max() if metrica == 'R2' else tabla_final[metrica].min()
    print(metrica, 'extremo favorable en población común:', tabla_final.loc[tabla_final[metrica].eq(valor),'Modelo'].tolist())
print('Los tres pipelines ML se exportaron entrenados sólo con TRAIN, sin declarar un ganador obligatorio.')

,Modelo,MAE,RMSE,R2,Observaciones_evaluadas,Series_evaluadas,Poblacion,Protocolo
0,Regresión Lineal,0.2306,0.5396,0.3219,3444,129,comun,"Secuencial semanal, parámetros fijos"
1,Random Forest,0.2270,0.5487,0.2989,3444,129,comun,"Secuencial semanal, parámetros fijos"
2,XGBoost,0.2252,0.5489,0.2984,3444,129,comun,"Secuencial semanal, parámetros fijos"
3,ARIMA (Optimizado ADF/AIC),0.2363,0.5797,0.2175,3444,129,comun,Multi-step desde origen fijo

,Modelo,Predicciones_originales,Predicciones_no_finitas,Observaciones_evaluadas,Series_evaluadas,Observaciones_comunes,Series_comunes,Observaciones_fuera_comun,Fraccion_observaciones_retenidas
0,Regresión Lineal,3940,0,3940,156,3444,129,496,0.8741
1,Random Forest,3940,0,3940,156,3444,129,496,0.8741
2,XGBoost,3940,0,3940,156,3444,129,496,0.8741
3,ARIMA (Optimizado ADF/AIC),3444,0,3444,129,3444,129,0,1.0000

MAE extremo favorable en población común: ['XGBoost']
RMSE extremo favorable en población común: ['Regresión Lineal']
R2 extremo favorable en población común: ['Regresión Lineal']
Los tres pipelines ML se exportaron entrenados sólo con TRAIN, sin declarar un ganador obligatorio.